name: Bryn Taylor | Personal Style Management
markdown: redcarpet
pygments: true
google_analytics_id: UA-XXXXXXXXX
url: http://bryntaylorstyle.com
description: "Wardrobe consulting and personal styling services for men and women."
